Repository hashicorp/cdktf-aws-cdk, pull requests merged in 2023-11, with the labels that each got.

#510 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, automated, dependencies

#523 chore(deps): upgrade dependencies
  .projen/deps.json
  .projen/tasks.json
  package.json
  yarn.lock
Labels: automerge, automated, dependencies

#538 chore(deps): upgrade dependencies
  package.json
  src/mapping/aws/events-role.ts
  yarn.lock
Labels: automerge, automated, dependencies

#541 chore: fix update-cdktf script
  .github/workflows/upgrade-cdktf.yml
  projenrc/upgrade-cdktf.ts
  scripts/update-cdktf.sh
Labels: automerge, auto-approve

#542 chore(deps): remove dependency on node-fetch
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/build.yml
  .github/workflows/lock.yml
  .github/workflows/provider-upgrade.yml
  .github/workflows/pull-request-lint.yml
  .github/workflows/release.yml
  .github/workflows/update-snapshots.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-node.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  projenrc/index.ts
  projenrc/upgrade-node.ts
  scripts/check-node-versions.js
  yarn.lock
Labels: auto-approve

#546 chore: fix incorrect version in README
  README.md
Labels: auto-approve

#544 chore: improve workflows
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/provider-upgrade.yml
  .github/workflows/update-snapshots.yml
  projenrc/auto-approve.ts
  projenrc/automerge.ts
  projenrc/provider-upgrade.ts
  projenrc/update-snapshots.ts
Labels: auto-approve

#545 chore(deps): upgrade jsii & typescript
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  projenrc/cdktf-config.ts
  projenrc/index.ts
  yarn.lock
Labels: dependencies, auto-approve

#549 chore(deps): upgrade dependencies
  .projen/deps.json
  .projen/tasks.json
  package.json
  yarn.lock
Labels: automerge, automated, dependencies

#547 feat: update CloudControl supported types
  scripts/update-supported-types.js
  src/awscc/supportedTypes.ts
Labels: auto-approve
