Repository hashicorp/cdktf-aws-cdk, pull requests merged in 2023-07, with the labels that each got.

#164 feat: upgrade AWS Cloud Control supported types
  src/awscc/supportedTypes.ts
Labels: automerge

#163 chore(deps): projen upgrade
  .projen/tasks.json
  package.json
  yarn.lock
Labels: automerge

#211 chore: fix various build issues
  .github/workflows/auto-approve.yml
  .github/workflows/provider-upgrade.yml
  .github/workflows/upgrade-main.yml
  projen/auto-approve.ts
  projen/index.ts
  projen/provider-upgrade.ts
Labels: auto-approve

#214 chore(deps): upgrade examples for security
  examples/typescript-cron-lambda/package-lock.json
  examples/typescript-cron-lambda/yarn.lock
  examples/typescript-manual-mapping/package-lock.json
  examples/typescript-manual-mapping/yarn.lock
  examples/typescript-step-functions-mixed/package-lock.json
  examples/typescript-step-functions-mixed/package.json
  examples/typescript-step-functions-mixed/yarn.lock
  examples/typescript-step-functions/package-lock.json
  examples/typescript-step-functions/package.json
  examples/typescript-step-functions/yarn.lock
Labels: auto-approve

#256 chore(deps): upgrade dependencies
  .github/workflows/pull-request-lint.yml
  .github/workflows/upgrade-main.yml
  .projen/deps.json
  .projen/tasks.json
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#288 chore: fix auto-approve workflow
  .github/workflows/auto-approve.yml
  projen/auto-approve.ts
Labels: automerge, auto-approve

#281 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve
