Repository hashicorp/cdktf-aws-cdk, pull requests merged in 2023-03, with the labels that each got.

#115 chore: add SUPPORT.md
  .github/SUPPORT.md
Labels: automerge

#118 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, dependencies

#119 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: dependencies
