Repository hashicorp/cdktf-aws-cdk, pull requests merged in 2023-08, with the labels that each got.

#302 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#315 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#329 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#352 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#359 chore: fix broken upgrade workflow
  .github/workflows/upgrade-cdktf.yml
  projen/upgrade-cdktf.ts
  scripts/update-cdktf.sh
Labels: auto-approve

#368 chore(ci): switch automerge to squash merges
  .github/workflows/automerge.yml
  projen/auto-merge.ts
Labels: automerge, auto-approve

#377 chore: automate upgrading Node.js
  .gitattributes
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-node.yml
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projenrc.ts
  README.md
  package.json
  projen/index.ts
  projen/upgrade-cdktf.ts
  projen/upgrade-node.ts
  scripts/check-node-versions.js
  scripts/update-cdktf.sh
  scripts/update-node.sh
  yarn.lock
Labels: automerge, auto-approve

#380 chore(ci): fix minor workflow issues
  .github/dependabot.yml
  .github/workflows/provider-upgrade.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-node.yml
  projen/index.ts
  projen/provider-upgrade.ts
  projen/upgrade-cdktf.ts
  projen/upgrade-node.ts
  scripts/check-node-versions.js
  scripts/update-node.sh
Labels: automerge, auto-approve

#387 chore(ci): improve workflows and allow upgrade-node job to succeed
  .github/dependabot.yml
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/build.yml
  .projenrc.ts
  projenrc/README.md
  projenrc/auto-approve.ts
  projenrc/auto-merge.ts
  projenrc/cdktf-config.ts
  projenrc/customized-license.ts
  projenrc/index.ts
  projenrc/lock-issues.ts
  projenrc/provider-upgrade.ts
  projenrc/semver.ts
  projenrc/upgrade-cdktf.ts
  projenrc/upgrade-node.ts
Labels: automerge, auto-approve

#398 chore: update snapshots in example tests
  examples/typescript-cron-lambda/package.json
  examples/typescript-manual-mapping/package.json
  examples/typescript-step-functions-mixed/package.json
  examples/typescript-step-functions/package.json
Labels: automerge, auto-approve

#399 chore!: upgrade minimum required aws-cdk-lib version to 2.80.0
  .gitignore
  .npmignore
  .projen/deps.json
  .projenrc.ts
  README.md
  examples/typescript-cron-lambda/main.test.ts
  examples/typescript-cron-lambda/package.json
  examples/typescript-cron-lambda/yarn.lock
  examples/typescript-manual-mapping/main.test.ts
  examples/typescript-step-functions-mixed/dist/fn-generate-id.js.map
  examples/typescript-step-functions-mixed/dist/fn-reverse-id.js.map
  examples/typescript-step-functions-mixed/main.test.ts
  examples/typescript-step-functions-mixed/package.json
  examples/typescript-step-functions-mixed/tsconfig.json
  examples/typescript-step-functions-mixed/yarn.lock
  examples/typescript-step-functions/main.test.ts
  examples/typescript-step-functions/package.json
  examples/typescript-step-functions/yarn.lock
  package.json
  projenrc/index.ts
  scripts/update-node.sh
  src/mapping/aws/ec2-vpc.d.ts
  src/mapping/aws/events-role.d.ts
  src/mapping/aws/iam-policy.d.ts
  src/mapping/aws/iam-role.d.ts
  src/mapping/aws/index.d.ts
  src/mapping/aws/lambda-permission.d.ts
  src/mapping/helper.d.ts
  src/mapping/index.d.ts
  yarn.lock
Labels: auto-approve, security

#401 chore: delete package-lock.json files
  examples/typescript-cron-lambda/package-lock.json
  examples/typescript-manual-mapping/package-lock.json
  examples/typescript-step-functions-mixed/package-lock.json
  examples/typescript-step-functions/package-lock.json
Labels: automerge, auto-approve

#404 chore(ci): create way for Dependabot to update test snapshots
  .gitattributes
  .github/workflows/update-snapshots.yml
  .gitignore
  .projen/files.json
  examples/typescript-cron-lambda/package.json
  examples/typescript-manual-mapping/package.json
  examples/typescript-step-functions-mixed/package.json
  examples/typescript-step-functions/package.json
  projenrc/index.ts
  projenrc/update-snapshots.ts
Labels: automerge, auto-approve

#405 chore: fix update-snapshots job
  .github/workflows/update-snapshots.yml
  projenrc/update-snapshots.ts
Labels: automerge, auto-approve

#403 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, automated, dependencies

#415 chore: remove charset from tsconfig files
  examples/typescript-cron-lambda/tsconfig.json
  examples/typescript-manual-mapping/tsconfig.json
  examples/typescript-step-functions-mixed/tsconfig.json
  examples/typescript-step-functions/tsconfig.json
Labels: automerge, auto-approve

#417 chore: remove hard-coded versions of jsii-docgen and rosetta
  .projen/deps.json
  .projen/tasks.json
  package.json
  projenrc/index.ts
  yarn.lock
Labels: automerge, auto-approve

#421 chore: add contributing guide and PR template
  .github/CONTRIBUTING.md
  .github/pull_request_template.md
Labels: automerge, auto-approve

#422 chore: enable prettier & eslint
  .eslintrc.json
  .gitattributes
  .gitignore
  .npmignore
  .prettierignore
  .prettierrc.json
  .projen/deps.json
  .projen/files.json
  .projen/tasks.json
  .projenrc.ts
  docs/cloudcontrolapiResource.md
  examples/typescript-cron-lambda/cdktf.json
  examples/typescript-cron-lambda/jest.config.js
  examples/typescript-cron-lambda/main.ts
  examples/typescript-manual-mapping/cdktf.json
  examples/typescript-manual-mapping/jest.config.js
  examples/typescript-manual-mapping/main.ts
  examples/typescript-step-functions-mixed/README.md
  examples/typescript-step-functions-mixed/cdktf.json
  examples/typescript-step-functions-mixed/fn-generate-id.ts
  examples/typescript-step-functions-mixed/jest.config.js
  examples/typescript-step-functions-mixed/main.test.ts
  examples/typescript-step-functions-mixed/main.ts
  examples/typescript-step-functions/README.md
  examples/typescript-step-functions/cdktf.json
  examples/typescript-step-functions/jest.config.js
  examples/typescript-step-functions/main.ts
  package.json
  projenrc/README.md
  projenrc/auto-approve.ts
  projenrc/automerge.ts
  projenrc/cdktf-config.ts
  projenrc/index.ts
  projenrc/provider-upgrade.ts
  projenrc/semver.ts
  projenrc/update-snapshots.ts
  projenrc/upgrade-cdktf.ts
  projenrc/upgrade-node.ts
  scripts/check-node-versions.js
  scripts/update-supported-types.js
  src/aws-adapter.ts
  src/es2019.ts
  src/mapping/EventualConsistencyWorkaroundAspect.ts
  src/mapping/aws/ec2-vpc.ts
  src/mapping/aws/events-role.ts
  src/mapping/aws/iam-policy.ts
  src/mapping/aws/iam-role.ts
  src/mapping/aws/index.ts
  src/mapping/aws/lambda-permission.ts
  src/mapping/helper.ts
  src/mapping/index.ts
  src/tests/aws-adapter.test.ts
  src/tests/aws-ecs.test.ts
  src/tests/aws-lambda-function.test.ts
  tsconfig.eslint.json
  yarn.lock
Labels: automerge, auto-approve

#423 chore: exclude .copywrite.hcl from published package
  .npmignore
  projenrc/index.ts
Labels: automerge, auto-approve

#424 chore: gitignore package-lock files
  examples/typescript-cron-lambda/.gitignore
  examples/typescript-manual-mapping/.gitignore
  examples/typescript-step-functions-mixed/.gitignore
  examples/typescript-step-functions/.gitignore
Labels: automerge, auto-approve

#425 fix: use link to new GitHub issue template for requesting CloudControl mappings
  src/mapping/index.ts
Labels: automerge, auto-approve
