Repository hashicorp/cdktf-aws-cdk, pull requests merged in 2024-08, with the labels that each got.

#860 chore(deps): upgrade dependencies
  .eslintrc.json
  .projen/tasks.json
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#863 chore(deps): upgrade dependencies
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-node.yml
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#871 chore(deps): update pinned versions of GitHub Actions
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/build.yml
  .github/workflows/provider-upgrade.yml
  .github/workflows/pull-request-lint.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-node.yml
  .projenrc.ts
  projenrc/index.ts
Labels: dependencies

#861 chore(deps): upgrade jsii & typescript to v5.4
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: automerge, auto-approve

#873 chore(deps): upgrade dependencies
  yarn.lock
Labels: automerge, dependencies, auto-approve

#881 chore(deps): upgrade dependencies
  .gitattributes
  .projen/tasks.json
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve
