Repository hashicorp/cdktf-aws-cdk, pull requests merged in 2025-04, with the labels that each got.

#1023 chore(ci): remove unnecessary compile step from workflow
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-jsii-typescript.yml
  .github/workflows/upgrade-node.yml
  projenrc/upgrade-cdktf.ts
  projenrc/upgrade-jsii-typescript.ts
  projenrc/upgrade-node.ts
Labels: automerge, auto-approve

#1026 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#1029 chore(deps): upgrade dependencies
  yarn.lock
Labels: automerge, dependencies, auto-approve

#1032 chore(deps): upgrade jsii & typescript to v5.6
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: automerge, automated, auto-approve

#1043 chore(deps): upgrade dependencies
  yarn.lock
Labels: automerge, dependencies, auto-approve

#1046 chore(deps): upgrade dependencies
  package.json
  tsconfig.dev.json
  yarn.lock
Labels: automerge, dependencies, auto-approve
