Repository hashicorp/cdktf-aws-cdk, pull requests merged in 2025-06, with the labels that each got.

#1068 chore(deps): upgrade jsii & typescript to v5.7
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: automerge, automated, auto-approve

#1022 chore!: increase minimum supported Node.js version to 20
  .eslintrc.json
  .github/workflows/build.yml
  .github/workflows/provider-upgrade.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-jsii-typescript.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-node.yml
  .projen/deps.json
  .projenrc.ts
  README.md
  examples/typescript-cron-lambda/package.json
  examples/typescript-manual-mapping/package.json
  examples/typescript-step-functions-mixed/package.json
  examples/typescript-step-functions/package.json
  package.json
  projenrc/cdktf-config.ts
  src/aws-adapter.ts
  src/mapping/aws/iam-role.ts
  yarn.lock
Labels: automerge, automated, security

#1075 chore(deps): upgrade dependencies
  yarn.lock
Labels: automerge, dependencies, auto-approve

#1084 chore(deps): update pinned versions of GitHub Actions
  .github/MAINTENANCE.md
  .github/workflows/build.yml
  .github/workflows/provider-upgrade.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-jsii-typescript.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-node.yml
  .projenrc.ts
Labels: automerge, auto-approve

#1085 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#1086 chore(deps): upgrade dependencies
  yarn.lock
Labels: automerge, dependencies, auto-approve

#1099 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#1108 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve
