Repository hashicorp/cdktf-aws-cdk, pull requests merged in 2025-01, with the labels that each got.

#974 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#980 chore(deps): update pinned versions of GitHub Actions
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/build.yml
  .github/workflows/provider-upgrade.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-node.yml
  .projenrc.ts
Labels: automerge, auto-approve

#981 chore(ci): add workflow for upgrading jsii & typescript
  .gitattributes
  .github/workflows/upgrade-jsii-typescript.yml
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  projenrc/cdktf-config.ts
  projenrc/index.ts
  projenrc/upgrade-jsii-typescript.ts
  scripts/update-jsii-typescript.sh
  yarn.lock
Labels: automerge, auto-approve

#982 chore: upgrade jsii & typescript to v5.5
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: automerge, automated, auto-approve

#984 docs: create maintenance guide
  .github/MAINTENANCE.md
Labels: automerge, auto-approve

#983 chore(ci): update required version of constructs when cdktf is upgraded
  .github/workflows/upgrade-cdktf.yml
  examples/typescript-cron-lambda/package.json
  examples/typescript-manual-mapping/package.json
  examples/typescript-step-functions-mixed/package.json
  examples/typescript-step-functions/package.json
  projenrc/upgrade-cdktf.ts
  scripts/update-cdktf.sh
  yarn.lock
Labels: automerge, auto-approve

#987 chore(ci): pin version of cssstyle to allow upgrade-main to succeed
  .projen/deps.json
  .projenrc.ts
  package.json
  projenrc/cdktf-config.ts
  projenrc/index.ts
  projenrc/semver.ts
  projenrc/util/random-cron.ts
  src/aws-adapter.ts
  src/es2019.ts
  src/mapping/EventualConsistencyWorkaroundAspect.ts
  src/mapping/aws/ec2-vpc.ts
  src/mapping/aws/events-role.ts
  src/mapping/helper.ts
  src/mapping/index.ts
  src/tests/aws-adapter.test.ts
  src/tests/aws-ecs.test.ts
  src/tests/aws-lambda-function.test.ts
  yarn.lock
Labels: automerge, auto-approve

#988 chore(ci): make upgrade-node workflow manually triggerable
  .github/MAINTENANCE.md
  .github/workflows/upgrade-node.yml
  projenrc/upgrade-node.ts
  scripts/check-node-versions.js
Labels: automerge, auto-approve

#989 chore(ci): make workflows consistent across Projen projects
  .github/MAINTENANCE.md
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projen/tasks.json
  package.json
  projenrc/auto-approve.ts
  projenrc/automerge.ts
  projenrc/cdktf-config.ts
  projenrc/upgrade-jsii-typescript.ts
  yarn.lock
Labels: automerge, auto-approve

#990 chore(deps): upgrade dependencies
  yarn.lock
Labels: automerge, dependencies, auto-approve

#992 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve
