Repository hashicorp/cdktf-aws-cdk, pull requests merged in 2025-02, with the labels that each got.

#994 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#995 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#998 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve

#1000 chore(deps): upgrade aws-cdk-lib in examples
  examples/typescript-cron-lambda/package.json
  examples/typescript-step-functions-mixed/main.test.ts
  examples/typescript-step-functions-mixed/package.json
  examples/typescript-step-functions/main.test.ts
  examples/typescript-step-functions/package.json
Labels: automerge, auto-approve

#1001 chore(deps): address security vulnerabilities
  .projen/deps.json
  package.json
  projenrc/cdktf-config.ts
  yarn.lock
Labels: automerge, auto-approve

#1002 chore(ci): add missing script that workflow depends on
  scripts/check-jsii-versions.js
Labels: auto-approve

#1003 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: automerge, dependencies, auto-approve
